In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
plt.rcParams["figure.figsize"] = [10,5]
# Ignore warnings

import warnings
# Set the warning filter to ignore FutureWarning
warnings.simplefilter(action = "ignore", category = FutureWarning)

## Step 1: **Data Exploration**

In [ ]:
df = pd.read_csv("/content/CAR DETAILS FROM CAR DEKHO.csv")

In [ ]:
df.head(10)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

# Step 2: **Feature Engineerig**

In [ ]:
fuel= pd.get_dummies(df['fuel'], drop_first = True)
seller_type= pd.get_dummies(df['seller_type'], drop_first = True)
transmission= pd.get_dummies(df['transmission'], drop_first = True)
owner = pd.get_dummies(df['owner'], drop_first = True)

In [ ]:
df = pd.concat([df,fuel,seller_type,transmission, owner], axis=1)
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Diesel,Electric,LPG,Petrol,Individual,Trustmark Dealer,Manual,Fourth & Above Owner,Second Owner,Test Drive Car,Third Owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,False,False,False,True,True,False,True,False,False,False,False
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,False,False,False,True,True,False,True,False,False,False,False
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,True,False,False,False,True,False,True,False,False,False,False
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,False,False,False,True,True,False,True,False,False,False,False
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,True,False,False,False,True,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,True,False,False,False,True,False,True,False,True,False,False
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,True,False,False,False,True,False,True,False,True,False,False
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,False,False,False,True,True,False,True,False,True,False,False
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,True,False,False,False,True,False,True,False,False,False,False
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,False,False,False,True,True,False,True,False,False,False,False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  4340 non-null   object
 1   year                  4340 non-null   int64
 2   selling_price         4340 non-null   int64
 3   km_driven             4340 non-null   int64
 4   fuel                  4340 non-null   object
 5   seller_type           4340 non-null   object
 6   transmission          4340 non-null   object
 7   owner                 4340 non-null   object
 8   Diesel                4340 non-null   bool
 9   Electric              4340 non-null   bool
 10  LPG                   4340 non-null   bool
 11  Petrol                4340 non-null   bool
 12  Individual            4340 non-null   bool
 13  Trustmark Dealer      4340 non-null   bool
 14  Manual                4340 non-null   bool
 15  Fourth & Above Owner  4340 non-null   bool
 16  Second Owner          4340 non-null   bool
 17  Test Drive Car        4340 non-null   bool
 18  Third Owner           4340 non-null   bool
dtypes: bool(11), int64(3), object(5)
memory usage: 318.0+ KB

In [ ]:
boolean_columns = ['Diesel','Electric','LPG', 'Petrol', 'Individual', 'Trustmark Dealer', 'Manual',
                   'Second Owner','Test Drive Car']
for column in boolean_columns:
    df[column] = df[column].astype(int)

In [ ]:
df.drop(['fuel','seller_type', 'transmission', 'owner','name'], inplace = True, axis = 1)

In [ ]:
df.drop(['Fourth & Above Owner','Third Owner'], inplace = True, axis = 1)

In [ ]:
df

,year,selling_price,km_driven,Diesel,Electric,LPG,Petrol,Individual,Trustmark Dealer,Manual,Second Owner,Test Drive Car
0,2007,60000,70000,0,0,0,1,1,0,1,0,0
1,2007,135000,50000,0,0,0,1,1,0,1,0,0
2,2012,600000,100000,1,0,0,0,1,0,1,0,0
3,2017,250000,46000,0,0,0,1,1,0,1,0,0
4,2014,450000,141000,1,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4335,2014,409999,80000,1,0,0,0,1,0,1,1,0
4336,2014,409999,80000,1,0,0,0,1,0,1,1,0
4337,2009,110000,83000,0,0,0,1,1,0,1,1,0
4338,2016,865000,90000,1,0,0,0,1,0,1,0,0
4339,2016,225000,40000,0,0,0,1,1,0,1,0,0

In [ ]:
x = df.drop('selling_price', axis = 1)
y= df['selling_price']

In [ ]:
from sklearn import preprocessing
pre_process =preprocessing.StandardScaler().fit(x)
x_transform = pre_process.fit_transform(x)

# Step 3: **Model Training & Evaluation**

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x_transform, y, test_size= .20, random_state=101)

# **Gradient Boosting**

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
gb_regressor = GradientBoostingRegressor()
gb_regressor.fit(x_train,y_train)
y_pred_gb = gb_regressor.predict(x_test)
GBr= mean_squared_error(y_pred_gb,y_test)
print('Gradient Boosting regression :', GBr)
rmse = np.sqrt(GBr)
print("Root Mean Squared  :", rmse)

Gradient Boosting regression : 77845805438.2938
Root Mean Squared  : 279008.6117636762

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
rf_regressor = RandomForestRegressor()
rf_regressor.fit(x_train, y_train)
y_pred_rf =rf_regressor.predict(x_test)
RFr= mean_squared_error(y_pred_rf, y_test)
print("Random Forest Model :", RFr)
rmse = np.sqrt(RFr)
print("Root Mean Squared  :", rmse)

Random Forest Model : 71201791022.36076
Root Mean Squared  : 266836.6373314593